language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 68747053ad1d976c4952bbcbca4a711c18d23510
 local_dir: dist
 on:
   branch: master