language: node_js
node_js:
 - "node"

cache: npm


deploy:
 provider: script
 script: bash ./deploy.sh
 skip_cleanup: true
 on:
   branch: master

# provider: pages
# skip_cleanup: true
# github_token: $GITHUB_TOKEN
# local_dir: dist
# target_branch: github.com/yxj0312/yxj0312.github.io.git